exports.createLinesToInsert = function (strikeToken, remoteToken){
	var tokenElementRegex = /^\s*<aura:token\s(\n|.)*?\/>/gm;

	var matches = strikeToken.match(tokenElementRegex);  //these are the token elements we have found
	var ourTokenMap = createMapfromTokenMatches(matches);

	var theirMatches = remoteToken.match(tokenElementRegex);  //these are the token elements we have found 
	var theirTokenMap = createMapfromTokenMatches(theirMatches);

	var diffMap = {};

	for(var prop in ourTokenMap){
		if(!theirTokenMap.hasOwnProperty(prop)){
			diffMap[prop] = ourTokenMap[prop];
		}
	}

	var linesToInsert = [];

	for(var prop in diffMap){
		var tmpStr = '';
		tmpStr = "\t<aura:token name=\"" + prop + "\" value=\"" + diffMap[prop] + "\" />\n";
		linesToInsert.push(tmpStr);
	}
	if(!linesToInsert.length == 0){
		linesToInsert.push('</aura:tokens>');
		linesToInsert.unshift('\t<!--Below generated by Strike-CLI -->\n');
		linesToInsert.unshift('\n');
	}

	return linesToInsert;
}

function createMapfromTokenMatches(matches){
	var tmpMap = {};
	matches.forEach(function(a){		
		var nameMatch = a.match(/name=(\"|\')(.+?)(\"|\')/); 
		var valueMatch = a.match(/value=(\"|\')(.+?)(\"|\')/);
		
		tmpMap[nameMatch[2]] = valueMatch[2];
	});

	return tmpMap;
}